### ISSUE TITLE
Missing research/blueprint_algo/flop_lossy_2.pkl file

### ISSUE THREAD

**Issue by jaimeggb** [fedden/poker_ai#153]
**Describe the bug**
> Step 5/10 : COPY "${LUT_DIR}/flop_lossy_2.pkl" . COPY failed: file not found in build context or excluded by .dockerignore: stat research/blueprint_algo/flop_lossy_2.pkl: file does not exist

**To Reproduce**
1. Run the ParentDockerfile
2. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - Browser chrome

**Additional context**

**Comment by mohsenamjadi** [comment]
@jaimeggb how did you solve this issue? when I want to run the ParentDockerfile it gives me this error:
 => ERROR [4/7] COPY research/blueprint_algo/flop_lossy_2.pkl .                                                    0.0s
 => ERROR [5/7] COPY research/blueprint_algo/preflop_lossless.pkl .                                                0.0s
 => ERROR [6/7] COPY research/blueprint_algo/river_lossy_2.pkl .                                                   0.0s
 => ERROR [7/7] COPY research/blueprint_algo/turn_lossy_2.pkl .
failed to compute cache key: "/research/blueprint_algo/turn_lossy_2.pkl" not found: not found


> **Describe the bug**
> 
> > Step 5/10 : COPY "${LUT_DIR}/flop_lossy_2.pkl" . COPY failed: file not found in build context or excluded by .dockerignore: stat research/blueprint_algo/flop_lossy_2.pkl: file does not exist
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run the ParentDockerfile
> 2. See error
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux
> * Python version: 3.7
> * Browser chrome
> 
> **Additional context**
