### ISSUE TITLE
running play with correct options still throws errors

### ISSUE THREAD

**Issue by btcgodx** [fedden/poker_ai#156]
running poker_ai play with all the correct options and paths still throws an error:

/poker_ai/terminal/runner.py", line 185, in run_terminal_app
    log.info(f"{current_player_name} chose {action}")
UnboundLocalError: local variable 'action' referenced before assignment

I can see some cards dealt but I am never able to input anything before that error comes

**Comment by shmmathur** [comment]
@btcgodx were you able to resolve this? I am stuck with the same error.
