### ISSUE TITLE
engine.py betting order

### ISSUE THREAD

**Issue by BruteforceAI** [fedden/poker_ai#36]
is it possible that the program doesn't follow this sequence of betting order?

ORDER
Player 1 – Button/Dealer
Player 2 – Small Blind 
Player 3 – Big Blind 
Player 4 – Under the Gun
Player 5 – Cut-Off

PRE FLOP: order: 4 – 5 – 1 – 2 – 3  
FLOP, TURN and RIVER: 2 – 3 – 4 – 5 – 1  

And a reset func for "is_active player" could be missing in case you wanna play two hands in a row sth like this:

    def reset_players_state(self):
        for player in self.players:
            if player.n_chips > 0:
                player.is_active = True

**Comment by BruteforceAI** [comment]
def _all_dealing_and_betting_rounds(self):
        self.table.dealer.deal_private_cards(self.table.players)
        print('----------- pre flop ------------')
        self._betting_round(preflop=True)                        # update first_round -> preflop
        self.table.dealer.deal_flop(self.table)
        print('------------ flop ---------------')
        self._betting_round()
        self.table.dealer.deal_turn(self.table)
        print('------------ turn ---------------')
        self._betting_round()
        self.table.dealer.deal_river(self.table)
        print('------------ river --------------')
        self._betting_round()

    def _players_in_order_of_betting(self, preflop):                       # update first_round -> preflop
        if preflop:
            return self.table.players[2:] + self.table.players[:2]
        return self.table.players

    def _all_active_players_take_action(self, preflop):                  # update first_round -> preflop
        for player in self._players_in_order_of_betting(preflop):         # update first_round -> preflop
            if player.is_active:
                self.state = player.take_action(self.state)

    def _bet_until_everyone_has_bet_evenly(self, preflop = False):     # update first_round -> preflop   
        first_round = True
        while first_round or self.more_betting_needed:
            self._all_active_players_take_action(preflop)           # otherwise in the middle of the round
            first_round = False                                  # will switch players betting order       
    
    def _betting_round(self, preflop = False):         # update first_round -> preflop
        if self.n_players_with_moves > 1:
            self._bet_until_everyone_has_bet_evenly(preflop)
        else:                                                           
            pass
        self._post_betting_analysis()

**Comment by fedden** [comment]
Hey I'm sorry I have got back to you so slowly. 

The poker engine class that you have been analysing is now a cog in the ShortDeckPokerState class, which is more suitable for depth-first search during MCCFR.

Do you still feel that the order is incorrect? It is my view that it's correct but of course I could be mistaken here.

**Comment by BruteforceAI** [comment]
![image](https://user-images.githubusercontent.com/62446333/78606013-e014b800-785c-11ea-99d0-166200abce63.png)

**Comment by fedden** [comment]
Thanks that is a super clear visualisation

**Comment by fedden** [comment]
@big-c-note what do you think about this? In the short deck poker state class I’m pretty sure we iterate over each player without any special ordering, and just like the strategy learn the appropriate move for that players turn, but I think so @BruteforceAI is pointing out we are doing it wrong in terms of the rules of the game, regardless of whether we use the poker engine class that @BruteforceAI is using here, or whether we use the short deck poker class which doesn’t call this method but is still incorrect in terms of player order (in a different manner to the poker engine)

**Comment by big-c-note** [comment]
Hey, I'll be back in debug mode tonight (9 AM currently), so I will take a look. Thanks for bringing it to our attention @BruteforceAI, I can vet it certainly

**Comment by fedden** [comment]
Hey so I've wrote a test and updated the logic for the ShortDeckPokerState class which can be found here. Hopefully the order of players is good now.
https://github.com/fedden/pluribus-poker-AI/blob/281d02c3e7d19b6d58250a6a4a05c89654462137/test/functional/test_short_deck.py#L90-L137

**Comment by fedden** [comment]
Will need to update the poker engine too - but currently we don't use that specific bit of code so not the highest priority at the moment.

**Comment by big-c-note** [comment]
Given that we aren't actively developing on that bit of code, I'm going to come back to this at a later time
