### ISSUE TITLE
Add a 'check' Action or Remove 'fold' Action When Not Facing a Bet

### ISSUE THREAD

**Issue by big-c-note** [fedden/poker_ai#54]
**Is your feature request related to a problem? Please describe.**
See [here](https://github.com/fedden/pluribus-poker-AI/blob/feature/WIP-debug-test-blueprint/research/blueprint_algo/example_output_debug.txt) for sample output of debug output. 

In this situation `I = cards_cluster=0, history=['call', 'call', 'fold']` on line 58. The dealer has called the 100 bet, the small blind has completed their bet to 100, and the big blind has folded. There are two inefficiencies in the actions here.

1) The big blind should never have to fold their big blind when facing no bet. In other words, they have already completed the small bet with their blind, they can simply check and wait to improve on the flop. 
2) For a similar reason, a player should never fold if they aren't facing a bet (really a generalization of the problem for # 1). In line 71, we see the player 0 (small blind) fold to no bet. They should simply check and await more info. It's possible other players will check and they will sneak into a set on the turn, for example.

This is a feature request because folding in these spots is a valid move, but there is no reason to explore it.

**Describe the solution you'd like**
Correct me if I'm wrong but the current behavior for `Player.call()` is to call 0 chips if they are not facing a bet, essentially the same as a check. So we would simply need to remove `fold` as a valid action `if n_chips_to_call == 0`. I'll add a PR below.

**Describe alternatives you've considered**

**Additional context**

**Comment by big-c-note** [comment]
#55 

^^PR

**Comment by fedden** [comment]
> There are two inefficiencies in the actions here.
>
> 1. The big blind should never have to fold their big blind when facing no bet. In other words, they have already completed the small bet with their blind, they can simply check and wait to improve on the flop.
> 2. For a similar reason, a player should never fold if they aren't facing a bet (really a generalization of the problem for # 1). In line 71, we see the player 0 (small blind) fold to no bet. They should simply check and await more info. It's possible other players will check and they will sneak into a set on the turn, for example.

1. Yes the big blind should never have to fold. It's a terrible strategy. 
2. Again in these scenarios, yes the sensible move is to remain in the hand and not fold.

However, this is something you'd hope a strategy would learn over time. Of course we could bake in this to the logic of the game, which in turn will change what legal moves can be made.

> This is a feature request because folding in these spots is a valid move, but there is no reason to explore it.

I wanna rest on this and make sure we don't want to rule out these nodes. We are baking in information about the pot into the information set and I wanna be sure that we aren't inadvertadly doing anything wrong. 

I'd be much happier if we made this behaviour optional, by adding a parameter to the constructor of the `ShortDeckPokerState` class, i.e: `prevent_unnecessary_folds: bool = False`

**Comment by big-c-note** [comment]
I like the suggested behavior as optional idea as a compromise. To be honest, the negative regret pruning should catch this behavior, but if it is certain that the aforementioned moves are negative EV, I don't see a reason to include them as valid actions. 

Let's let it sit for now, and when I get through of some of my other work, I'll see how it ranks in terms of priority. If the bot is learning slowly, this could be a good optimization.
