### ISSUE TITLE
Can I set the board card, hand card (basically set environment manually)

### ISSUE THREAD

**Issue by ericntunctu** [fedden/poker_ai#66]
Hi, thanks for the really good project.
I am wondering that can I set the boarding card, hand card (basically set environment manually) and also set the hand what AI gets. Then I want to see what Ai will do in every particular situation?
I want to directly use your AI result and see what AI will do in each situation.

Thanks

**Comment by big-c-note** [comment]
You're welcome! Yes this is possible. The strategy of the bot is stored in a dictionary. The strategy is represented as probabilities for taking each action with the key being the information you describe. 

At our current stage it will be tricky to explain to you how this is done, and you would not find the results helpful most likely. Currently we are working on a contrived game of poker.

But, had you trained a bot for several days, you could look up its strategy in particular information/action sequences (ie; what you are requesting).

I would suggest continuing to follow the project, and when we release a first iteration of the bot, this issue can be better answered.

**Comment by ericntunctu** [comment]
Thanks, I am very excited to do see the future of this project
