### ISSUE TITLE
Test your Poker Agents on pokerwars.io

### ISSUE THREAD

**Issue by systats** [fedden/poker_ai#83]
Hi Guys,

just wanna let you know that there is a Free Poker Bot Platform to test your agents in a more heterogenous environment. I think the current bots are already pretty competitive although it would be nice to compete against more ml experts. There are around 20-40 bots online almost 24/7.

Jump to [pokerwars leaderboard](https://www.pokerwars.io/stats) or check out several API languages on [pokerwars github](https://github.com/pokerwars)

Hope to see some of you there and exchange some insights.

Cheers,
Simon

**Comment by fedden** [comment]
Oh awesome, thanks Simon! Will definitely look into this 👍

**Comment by fedden** [comment]
Out of interest, do you know of anyone who are writing bots on your platform using algorithms based on CFR?

**Comment by systats** [comment]
I have just started now to cheer up the github community around poker bots, because this platform is really cool to test ideas fast and in a competitive way. And clearly too few know about it. CFR specifically not so far. Personally I use a neural network for card understanding and win probability calculations. But I would love to see CFR in action.

**Comment by big-c-note** [comment]
Dope. Good call

**Comment by systats** [comment]
BTW I am in contact with pokerwars in order to further improve their service (which is just a side project for them). So if you have any suggestions pls put it in their python issues...
