### ISSUE TITLE
How to run mullitprocessing short deck blueprint algo 

### ISSUE THREAD

**Issue by Red-Giuliano** [fedden/poker_ai#90]
**Describe the bug**

I cannot seem to run the multiprocessing blueprint algo because the .pkl files requested do not exist in the repository

**To Reproduce**
1. Go to path 'research/multiprocessing_blueprint/' 
2. Run command 'python main.py search'
3. Check output of

 'ValueError: File path not found ../blueprint_algo/preflop_lossless.pkl. Ensure pickle_dir is set to directory containing pickle files'

The only dir containing .pkl files is /clustering/data. However, when I point to those files I get the following message 

''ValueError: probabilities do not sum to 1"

**Expected behavior**
Normal training without error messages 

**Screenshots**
Happy to take them if they would help 

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version: 3.7

**Additional context**

**Comment by Red-Giuliano** [comment]
is it necessary to run infromation_acbstraction.py?

**Comment by big-c-note** [comment]
Hey @Red-Giuliano , thanks for your interest in the repo.

In the coming weeks we'll be creating documentation and a release schedule that will allow us to better support this question. At the moment I can say that you have to train your own strategies/card clustering, so to answer your question, yes. Please stay tuned as we're working on documenting this process. I'll leave this issue open, and we can link to the documentation when the time comes. 

Issue to watch:
#99

**Comment by big-c-note** [comment]
@Red-Giuliano , see updated readme for information.
