### ISSUE TITLE
Error probability

### ISSUE THREAD

**Issue by ttys0001** [fedden/poker_ai#92]
**Describe the bug**
Why are the strategy generated by this file(async_blueprint_short_deck_poker.py) not worked well?
Because we find that the probabilty of three actions is [0.33333,0.33333,0.33333] by the terminal.

So does it mean that the probability is not updated during training?

**To Reproduce**
1. Run the script async_blueprint_short_deck_poker.py
2. Run command 'python -m pluribus.terminal.runner --agent offline --pickle_dir research/blueprint_algo --strategy_path research/blueprint_algo/strategy_6700.gz --no_debug_quick_start'
3. See output probability 

**Screenshots**
![bug.png](https://i.loli.net/2020/05/20/5klaUbW4X8r9BZ3.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Python version: 3.7

**Comment by Red-Giuliano** [comment]
How are you able to run async_blueprint_short_deck_poker.py? I keep getting the error

--probabilities don't sum to 1 (see issue #90)

**Comment by ttys0001** [comment]
The author did not provide the pkl file of 20 cards generated by information_abstraction. 

You need to generate this file yourself. That will need one day to generate.

**Comment by ttys0001** [comment]
> How are you able to run async_blueprint_short_deck_poker.py? I keep getting the error
> 
> --probabilities don't sum to 1 (see issue #90)

The author did not provide the pkl file of 20 cards generated by information_abstraction.

You need to generate this file yourself. That will need one day to generate.
