### ISSUE TITLE
Last remaining player is prompted to act

### ISSUE THREAD

**Issue by MadsAdrian** [fedden/poker_ai#95]
https://github.com/fedden/poker_ai/blob/c4eb048d5373c2002941227c23e9fd9397d50f96/pluribus/poker/engine.py#L168-L184

The logic here seems somewhat flawed. If only one player remains 'movable', it is still prompted to act. E.g. if SB and BB is heads-up and the SB `folds`, the BB can potentially fold as well leaving no active players. 

Something like 
```python
if self.n_players_with_moves() < 2:
    break
```
(within the loop) on line 175 would solve this issue, but I'm not sure this does not break some other logic (e.g. side-pot action).

**Comment by fedden** [comment]
Hi @MadsAdrian thanks for the comment. Check out the Logic in the ShortDeckPokerState class as that is what is used primarily to manage a game, a lot of the poker engine logic is unclearly deprecated as it was a first pass at encoding the rules into a usable class

**Comment by fedden** [comment]
Opened up a new issue to track this #96 , I will close this issue for now, thanks again for going through the code
