### ISSUE TITLE
Can't find strategy gz file

### ISSUE THREAD

**Issue by adamkleingit** [fedden/poker_ai#98]
Hi,
first of all thanks for this Repo!

I was trying to run the terminal runner using the command from the README file:
```
    python -m pluribus.terminal.runner                                       \
        --agent offline                                                      \
        --pickle_dir ./research/blueprint_algo                               \
        --strategy_path ./research/blueprint_algo/offline_strategy_285800.gz \
        --no_debug_quick_start
```

But got some errors on the pickle_dir.
I changed it to point to './research/clustering/data' and also changed:
```
            "flop_lossy_2.pkl",
            "turn_lossy_2.pkl",
            "river_lossy_2.pkl",
```
to:
```
            "flop_lossy.pkl",
            "turn_lossy.pkl",
            "river_lossy.pkl",
```
But I still have an error on not finding the strategy gz file. Is that something I can create from the code somehow? Or is it available outside the git repo?

Thanks!

**Comment by big-c-note** [comment]
Hey Adam, thanks for your interest in the repo. 

In the coming weeks we'll be creating documentation and a release schedule that will allow us to better support this question. At the moment I can say that you have to train your own strategy. Please stay tuned as we're working on documenting this process. I'll leave this issue open, and we point link to the documentation when the time comes.

**Comment by big-c-note** [comment]
#99

**Comment by adamkleingit** [comment]
Thanks for the work you're doing!

**Comment by fedden** [comment]
please see further documentation of the process from the README file :)

**Comment by amirfarazmand** [comment]
Adam were you able to fin the .pkl file, I get this error
 ValueError: File path not found .\preflop_lossless.pkl. Ensure lut_path is set to directory containing pickle files

**Comment by amirfarazmand** [comment]
I cant find any doc regarding the strategy file, is anyway to share this file?

 File "C:\Users\Amir\PycharmProjects\poker_ai\poker_ai\terminal\runner.py", line 66, in run_terminal_app
    offline_strategy = offline_strategy_dict['strategy']
KeyError: 'strategy'
